### ISSUE TITLE
Cannot build the project due to missing Makefile target

### ISSUE THREAD

**Issue by firebolt55439** [kisonecat/web2js#6]
Multiple problems building project:

For `Makefile`, target `bigmem.ch` does not exist, therefore does not compile.

Even if removing `bigmem.ch` and `bigmem-changes.ch` from `Makefile`, got a very obscure error in `node compile.js` (something about jump target label 9998 not found).

Hoping to use this in a project with circuitikz, would very much appreciate you checking this error out. I suspect perhaps you did not `git add` all your .ch files from local (specifically, `bigmem.ch`)?

I am running on Ubuntu with full TeXLive in case that helps.

**Comment by kisonecat** [comment]
9a6aad4485505b4e0a6220935021887baaf1a2ca fixes the missing `bigmem.ch`.  I am sorry about my oversight there.

For label 9998, that is the `end_of_TEX` which is a nonlocal goto and should be fixed by `jstex/nonlocal-goto.ch`.  So I am not sure about this---in any case, please try again and let me know how it goes!

**Comment by firebolt55439** [comment]
That fixed the compilation issue! Very much appreciated :). 

(Also unrelated: `node-kpathsea` has no version 1.1.0 available as specified in the `package.json` file, leading to an error for `npm install` -- I patched it to use `kpsewhich` via `spawnSync` instead)

**Comment by jjavierdguezas** [comment]
> That fixed the compilation issue! Very much appreciated :).
> 
> (Also unrelated: `node-kpathsea` has no version 1.1.0 available as specified in the `package.json` file, leading to an error for `npm install` -- I patched it to use `kpsewhich` via `spawnSync` instead)

Hi @firebolt55439 can you please describe in more detail how you solve the `node-kpathsea` issue? 🙏🏻 thanks in advance
