### ISSUE TITLE
Web deployment core.dump size

### ISSUE THREAD

**Issue by firebolt55439** [kisonecat/web2js#7]
In your `tikzjax` project, you were able to deploy the `core.dump` file with only 500 KB of WASM. However, my `core.dump` is ~160MB due to the 2500 pages of memory. How did you have such a lightweight deployment package?

My goal is to enable `circuitikz`, `amsmath`, and `siunitx` support for `tikzjax` basically.

**Comment by firebolt55439** [comment]
Perhaps there's some way I can reduce the number of pages used?

**Comment by kisonecat** [comment]
A quick thing: the client grabs a gzip'd core.dump, so you might try `gzip -9 core.dump` and see how small it becomes.  It compresses well; my 163mb core.dump compresses to 2.1 megabytes.

Reducing the number of pages is one right thing to do -- unfortunately it must be done in multiple places right now.  I will work on making that clearer.

You can also fiddle with the memory layout, but it isn't super obvious how to do this, e.g., it depends on messing with `bigmem.ch` to change how TeX sets up memory.  A very frustrating point is TeX makes significant use of these packed `memory_word`s, which I'd prefer to be 32 bits wide, but `mem_max` must be smaller than `max_halfword`, so 32 bit words means memory would be limited to 64k words, which I don't think is enough for TikZ.  So the word size is set to 64 bits.

TeX Live in `texmf.cnf` seems to have `main_memory = 5000000`.  I set `mem_max` to 8 million, meaning 8 million words (!), which is where one gets to 160 megabytes.  This is surely overkill!  It would be good to know the right value.  There's definitely room for improving this.

**Comment by firebolt55439** [comment]
Ah that makes sense, I will compress the core and follow that approach.
